Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;

namespace assignment4.Controllers
{
    public class NewReport
    {
        public Guid SetId { get; set; }
    }

    [Authorize(Roles="Teacher")]
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            /* var applicationDbContext = _context.Report
                .Include(r => r.Set)
                .Include(r => r.ViewCount); */
            var reportset = await _context.Report
                .Include(r => r.Set)
                .Include(r => r.ViewCount)
                .ToListAsync();
            var ratings = await _context.SetRatingv3
                .ToListAsync();

            List<Report> reports = new();

            for (int i = 0; i < reportset.Count; i++)
            {
                Report report = new()
                {
                    ReportId = reportset[i].ReportId,
                    SetId = reportset[i].SetId,
                    Set = reportset[i].Set,
                    ViewCountId = reportset[i].ViewCountId,
                    ViewCount = reportset[i].ViewCount,
                    Ratings = ratings
                };
                report.CalculateAverageRating();
                reports.Add(report);
            }

            return View(reports);
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.ViewCount)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            
            if (report == null)
            {
                return NotFound();
            }

            // FlashcardSet set = GetSetById(report.SetId);
            FlashcardSet set = await _context.FlashcardSet
                .Include(s => s.User)
                .FirstOrDefaultAsync(s => s.SetId == report.SetId);
            report.Set = set;

            return View(report);
        }

        private FlashcardSet GetSetById(Guid SetId)
        { 
            return _context.FlashcardSet.FirstOrDefault(s => s.SetId == SetId);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
            ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name");
            return View();
        }

        private List<FlashcardSet> GetNonDeletedSets()
        {
            return _context.FlashcardSet.Where(set => !set.IsDeleted).ToList();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid SetId)
        {
            Report report = new() { SetId = SetId };

            // Check if there is already a report for the given SetId
            if (ReportExists(report.SetId))
            {
                ViewData["ErrorMessage"] = "A report already exists for this set.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            var set = await _context.FlashcardSet
                .FirstOrDefaultAsync(set => set.SetId == report.SetId);
            
            if (set == null)
            {
                ViewData["ErrorMessage"] = "This set does not exist.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            if (set.IsDeleted == true)
            {
                ViewData["ErrorMessage"] = "Cannot create a report on a deleted set.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            var ViewCount = await _context.ViewCount
                .FirstOrDefaultAsync(vc => vc.SetId == report.SetId);

            if (ViewCount == null)
            {
                ViewData["ErrorMessage"] = "Cannot create a report on a set without any views.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            if (ModelState.IsValid)
            {
                report.ReportId = Guid.NewGuid();
                report.ViewCountId = ViewCount.ViewCountId;
                _context.Add(report);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(report);
        }

        // GET: Reports/Edit/5
        /* public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report.FindAsync(id);
            if (report == null)
            {
                return NotFound();
            }
            ViewData["ViewCountId"] = new SelectList(_context.ViewCount, "ViewCountId", "ViewCountId", report.ViewCountId);
            return View(report);
        } */

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /* [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ReportId,SetId,ViewCountId")] Report report)
        {
            if (id != report.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(report);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportExists(report.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ViewCountId"] = new SelectList(_context.ViewCount, "ViewCountId", "ViewCountId", report.ViewCountId);
            return View(report);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.ViewCount)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }
        */

        //POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Report == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Report'  is null.");
            }
            var report = await _context.Report.FindAsync(id);
            if (report != null)
            {
                _context.Report.Remove(report);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        } 

        private bool ReportExists(Guid id)
        {
            return (_context.Report?.Any(e => e.SetId == id)).GetValueOrDefault();
        }
    }
}

Controllers/SetRatingv3Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace assignment4.Controllers
{
    [Authorize]
    public class SetRatingv3Controller : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly string loggedInUserId;

        public SetRatingv3Controller(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            loggedInUserId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        // Unused
        // GET: SetRatingv3
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.SetRatingv3.Include(s => s.FlashcardSet);
            return View(await applicationDbContext.ToListAsync());
        }

        //GET: SetRatingv3/RatingsForSet?SetId=f51060b6-2a9e-4c6a-a4cb-137dda19811f
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> RatingsForSet(Guid? SetId)
        {
            var setRatings = await _context.SetRatingv3
                .Include(s => s.FlashcardSet)
                .Where(sr => sr.RatedSetId == SetId)
                .ToListAsync();

            foreach (var rating in setRatings)
            {
                var user = await _context.Users.FindAsync(rating.RatingUserId);
                if (user != null)
                {
                    rating.RatingUserName = user.UserName;
                }

                var set = await _context.FlashcardSet.FindAsync(rating.RatedSetId);
                if (set != null)
                {
                    rating.RatedSetName = set.Name;
                }
            }

            return View(setRatings);
        }

        // GET: SetRatingv3/Details/5
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.SetRatingv3 == null)
            {
                return NotFound();
            }


            var setRatingv3 = await _context.SetRatingv3
                .Include(s => s.FlashcardSet)
                .FirstOrDefaultAsync(m => m.SetRatingId == id);
            if (setRatingv3 == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(setRatingv3.RatingUserId);
            if (user != null)
            {
                setRatingv3.RatingUserName = user.UserName;
            }


            return View(setRatingv3);
        }

        // GET: SetRatingv3/Create
        [Authorize(Roles = "Teacher, Student")]
        public IActionResult Create()
        {
            // ViewData["RatedSetId"] = new SelectList(_context.FlashcardSet, "SetId", "SetId");
            ViewData["RatedSetId"] = new SelectList(FlashcardSetsController.GetNonDeletedSets(_context), "SetId", "Name");
            return View();
        }

        // POST: SetRatingv3/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Create([Bind("SetRatingId,RatingUserId,RatingUserName,RatedSetId,RatedSetName,Rating,Comment,RatedDate")] SetRatingv3 setRatingv3)
        {
            if (ModelState.IsValid)
            {
                setRatingv3.SetRatingId = Guid.NewGuid();
                setRatingv3.RatingUserId = loggedInUserId;

                setRatingv3.RatedDate = DateTime.Now;
                _context.Add(setRatingv3);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "FlashcardSets");

            }

            ViewData["RatedSetId"] = new SelectList(_context.FlashcardSet, "SetId", "SetId", setRatingv3.RatedSetId);
            return View(setRatingv3);
        }

        // GET: SetRatingv3/Edit/5
        //[Authorize(Roles = "Teacher")]
        //public async Task<IActionResult> Edit(Guid? id)
        //{
        //    if (id == null || _context.SetRatingv3 == null)
        //    {
        //        return NotFound();
        //    }

        //    var setRatingv3 = await _context.SetRatingv3.FindAsync(id);
        //    if (setRatingv3 == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["RatedSetId"] = new SelectList(_context.FlashcardSet, "SetId", "SetId", setRatingv3.RatedSetId);
        //    return View(setRatingv3);
        //}

        // POST: SetRatingv3/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Teacher")]
        //public async Task<IActionResult> Edit(Guid id, [Bind("SetRatingId,RatingUserId,RatingUserName,RatedSetId,RatedSetName,Rating,Comment,RatedDate")] SetRatingv3 setRatingv3)
        //{
        //    if (id != setRatingv3.SetRatingId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(setRatingv3);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!SetRatingv3Exists(setRatingv3.SetRatingId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["RatedSetId"] = new SelectList(_context.FlashcardSet, "SetId", "SetId", setRatingv3.RatedSetId);
        //    return View(setRatingv3);
        //}

        //// GET: SetRatingv3/Delete/5
        //[Authorize(Roles = "Teacher")]
        //public async Task<IActionResult> Delete(Guid? id)
        //{
        //    if (id == null || _context.SetRatingv3 == null)
        //    {
        //        return NotFound();
        //    }

        //    var setRatingv3 = await _context.SetRatingv3
        //        .Include(s => s.FlashcardSet)
        //        .FirstOrDefaultAsync(m => m.SetRatingId == id);
        //    if (setRatingv3 == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(setRatingv3);
        //}

        //// POST: SetRatingv3/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = "Teacher")]
        //public async Task<IActionResult> DeleteConfirmed(Guid id)
        //{
        //    if (_context.SetRatingv3 == null)
        //    {
        //        return Problem("Entity set 'ApplicationDbContext.SetRatingv3'  is null.");
        //    }
        //    var setRatingv3 = await _context.SetRatingv3.FindAsync(id);
        //    if (setRatingv3 != null)
        //    {
        //        _context.SetRatingv3.Remove(setRatingv3);
        //    }
            
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool SetRatingv3Exists(Guid id)
        {
          return (_context.SetRatingv3?.Any(e => e.SetRatingId == id)).GetValueOrDefault();
        }


        //POST: SetRatingv3/AverageRating?SetId=f51060b6-2a9e-4c6a-a4cb-137dda19811f
        [HttpPost]
        [Authorize(Roles = "Teacher, Student")]
        public async Task<ActionResult> AverageRating(Guid SetId)
        {
            var ratings = await _context.SetRatingv3
                .Where(s => s.RatedSetId == SetId)
                .Select(s => s.Rating)
                .ToListAsync();

            var average = ratings.Average();

            return Content(average.ToString());
        }
    }
}

Views/Reports/Create.cshtml
@model assignment4.Models.Report

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Report</h4>
<hr />
@if (ViewData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData["ErrorMessage"]
    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SetId" class="control-label">Set Name</label>
                <select asp-for="SetId" class="form-control" asp-items="ViewBag.SetId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" id="padding-index"/>
            </div>
        </form>
        <div>
            <a asp-action="Index" class="btn btn-sm btn-secondary">Back to List</a>
        </div>
    </div>
</div>

<style>
    #padding-index {
        margin-bottom: 10px;
        margin-top: 10px;
    }
</style>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Reports/Delete.cshtml
@model assignment4.Models.Report

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Report</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Set.SetId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ViewCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ViewCount.ViewCountId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReportId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Reports/Details.cshtml
@model assignment4.Models.Report

@{
    ViewData["Title"] = "Report";
}

<body onload="GetAverageRating('@Model.SetId.ToString()')">
    <h1>@Html.DisplayFor(model => model.Set.Name)</h1>

    <div>
        <h4>Report</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Set ID
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.SetId)
            </dd>
            <dt class="col-sm-2">
                Set Name
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.Name)
            </dd>
            <dt class="col-sm-2">
                Views
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ViewCount.Count)
            </dd>
            <dt class="col-sm-2">
                Average Rating
            </dt>
            <dd class="col-sm-10" id="average-rating-in-report-details">

            </dd>
            <dt class="col-sm-2">
                Created Date
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.CreatedDate)
            </dd>
            <dt class="col-sm-2">
                Last Updated
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.UpdatedDate)
            </dd>
            <dt class="col-sm-2">
                Category
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.Category)
            </dd>
            <dt class="col-sm-2">
                Description
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.Description)
            </dd>
            <dt class="col-sm-2">
                Created by
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Set.User.UserName)
            </dd>
            <dt class="col-sm-2">
                See ratings 
            </dt>
            <dd class="col-sm-10">
                @Html.ActionLink("Ratings for Set", "RatingsForSet", "SetRatingv3", new { SetId = Model.SetId }, new { @class = "btn btn-sm btn-dark" })
            </dd>
            <dt class="col-sm-2">
                Go to set study screen
            </dt>
            <dd class="col-sm-10">
                @Html.ActionLink("Set Study screen", "Study", "FlashcardSets", new { id = Model.SetId }, new { @class = "btn btn-sm btn-dark" })
            </dd>
            <dt class="col-sm-2">
                View set
            </dt>
            <dd class="col-sm-10">
                @Html.ActionLink("View", "Details", "FlashcardSets", new { id = Model.SetId }, new { @class = "btn btn-sm btn-dark" })
            </dd>
            <dt class="col-sm-2">
                Edit set
            </dt>
            <dd class="col-sm-10">
                @Html.ActionLink("Edit", "Edit", "FlashcardSets", new { id = Model.SetId }, new { @class = "btn btn-sm btn-dark" })
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Index" class="btn btn-secondary">Exit</a>
    </div>
</body>

Views/Reports/Edit.cshtml
@model assignment4.Models.Report

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Report</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReportId" />
            <div class="form-group">
                <label asp-for="SetId" class="control-label"></label>
                <select asp-for="SetId" class="form-control" asp-items="ViewBag.SetId"></select>
                <span asp-validation-for="SetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ViewCountId" class="control-label"></label>
                <select asp-for="ViewCountId" class="form-control" asp-items="ViewBag.ViewCountId"></select>
                <span asp-validation-for="ViewCountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Reports/Index.cshtml
@model IEnumerable<assignment4.Models.Report>

@{
    ViewData["Title"] = "Reports";
}

<h1>Reports</h1>

<div class="row">
    <div class="col-md-2">
        <a asp-action="Create" class="btn btn-sm btn-dark">Start tracking a new set</a>
    </div>
    <p class="col-sm-6">
        Once a report is generated for a set, the report will be updated in live time.
    </p>

    <div class="table-responsive">
        <table class="table table-striped table-sm" id="report-index-table">
            <thead>
                <tr>
                    <th scope="col">Set Name</th>
                    <th scope="col">Times Studied</th>
                    <th scope="col">Average Rating</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="clickable-row" data-url="@Url.Action("Details", new { id = item.ReportId })">
                        <td><b>@item.Set.Name</b></td>
                        <td>@Convert.ToInt32(item.ViewCount?.Count ?? 0)</td>
                        <td>@Convert.ToInt32(item.AverageRating)</td>
                        <td><a class="btn btn-sm btn-dark" asp-action="Details" asp-route-id="@item.ReportId">Full Report</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    @{
        var serializerSettings = new Newtonsoft.Json.JsonSerializerSettings
        {
            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
        };
        // Filter the objects based on their type and property name before serialization
        var sets = Model.Where(x => x.GetType() == typeof(Report) && ((Report)x).Set != null).Select(x => ((Report)x).Set).ToList();
        var json = Newtonsoft.Json.JsonConvert.SerializeObject(sets, serializerSettings);
    }
    
<div class="d-flex justify-content-center">
    <div class="w-50 h-50">
        <h2>Total Sets by Category</h2>
        <canvas id="categorieschart" width="400" height="400"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js" integrity="sha384-YAshAm4KKjf8V01c4sdNbPYiwU0D0Q82fjMHhKw8VvP0ecY4fxXsZAHxC4r4Ei+T" crossorigin="anonymous"></script>

<script>
    var sets = @Html.Raw(json);
    const categories = {};
    sets.forEach(set => {
        if (set.Category in categories) {
            categories[set.Category] += 1;
        } else {
            categories[set.Category] = 1;
        }
    });

    const uniqueCategories = Object.keys(categories);
    const categoryCounts = Object.values(categories);
    const ctx = document.getElementById('categorieschart');

    const data = {
        labels: uniqueCategories,
        datasets: [{
            data: categoryCounts,
            hoverOffset: 4
        }]
    };
    const config = {
        type: 'pie',
        data: data
    };

    new Chart(ctx, config);

</script>

    <style>
        .clickable-row:hover {
            cursor: pointer;
            background-image: linear-gradient(113.9deg, rgb(255, 128, 0) -4.5%, rgb(255, 215, 0) 98.8%);
        }

        .btn-sm {
            text-decoration: none;
            min-width: 69px;
            display: inline-block;
            text-align: center;
        }
    </style>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const rows = document.querySelectorAll('.clickable-row');
            rows.forEach(row => {
                row.addEventListener('click', function (e) {
                    // Prevent click event for actions within the row
                    if (e.target.tagName === 'A') {
                        return;
                    }
                    const url = this.dataset.url;
                    if (url) {
                        window.location.href = url;
                    }
                });
            });
        });
    </script>