Controllers/FlashcardsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace assignment4.Controllers
{
    public class FlashcardsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly string loggedInUserId;

        public FlashcardsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            loggedInUserId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }


        // GET: Flashcards
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Flashcard
                .Include(f => f.FlashcardSet)
                .Include(f => f.User)
                .Where(f => f.IsDeleted == false);
            return View(await applicationDbContext.ToListAsync());
        }
        
        // GET: Flashcards/Details/5
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Flashcard == null)
            {
                return NotFound();
            }

            var flashcard = await _context.Flashcard
                .Include(f => f.FlashcardSet)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FlashcardId == id);
            if (flashcard == null)
            {
                return NotFound();
            }

            return View(flashcard);
        }

        // GET: Flashcards/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            //ViewData["SetId"] = new SelectList(_context.FlashcardSet, "SetId", "Name");
            ViewData["SetId"] = new SelectList(FlashcardSetsController.GetNonDeletedSets(_context), "SetId", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["User"] = new SelectList(_context.Users, "UserName", "UserName");
            return View();
        }

        // POST: Flashcards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create([Bind("FlashcardId,Front,Back,SetId,UserId,CreatedDate,UpdatedDate,IsDeleted")] Flashcard flashcard)
        {
            if (ModelState.IsValid)
            {
                flashcard.FlashcardId = Guid.NewGuid();
                flashcard.UserId = loggedInUserId;
                flashcard.CreatedDate = DateTime.Now;
                flashcard.UpdatedDate = DateTime.Now;
                flashcard.IsDeleted = false;
               
                _context.Add(flashcard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SetId"] = new SelectList(_context.FlashcardSet, "SetId", "Name", flashcard.SetId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "User", flashcard.UserId);
            
            return View(flashcard);
        }

        // GET: Flashcards/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Flashcard == null)
            {
                return NotFound();
            }

            var flashcard = await _context.Flashcard.FindAsync(id);
            if (flashcard == null)
            {
                return NotFound();
            }
            ViewData["SetId"] = new SelectList(FlashcardSetsController.GetNonDeletedSets(_context), "SetId", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["User"] = new SelectList(_context.Users, "UserName", "UserName");

            return View(flashcard);
        }

        // POST: Flashcards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(Guid id, [Bind("FlashcardId,Front,Back,SetId,UserId,CreatedDate,UpdatedDate,IsDeleted")] Flashcard flashcard)
        {
            if (id != flashcard.FlashcardId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    flashcard.UpdatedDate = DateTime.Now;
                    _context.Update(flashcard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlashcardExists(flashcard.FlashcardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SetId"] = new SelectList(_context.FlashcardSet, "SetId", "Name", flashcard.SetId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "User", flashcard.UserId);
            return View(flashcard);
        }

        // GET: Flashcards/Delete/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Flashcard == null)
            {
                return NotFound();
            }

            var flashcard = await _context.Flashcard
                .Include(f => f.FlashcardSet)
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.FlashcardId == id);
            if (flashcard == null)
            {
                return NotFound();
            }

            return View(flashcard);
        }

        // POST: Flashcards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Flashcard == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Flashcard'  is null.");
            }
            var flashcard = await _context.Flashcard.FindAsync(id);
            if (flashcard != null)
            {
                // _context.Flashcard.Remove(flashcard);
                flashcard.IsDeleted = true;
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlashcardExists(Guid id)
        {
          return (_context.Flashcard?.Any(e => e.FlashcardId == id)).GetValueOrDefault();
        }
    }
}

Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;

namespace assignment4.Controllers
{
    public class NewReport
    {
        public Guid SetId { get; set; }
    }

    [Authorize(Roles="Teacher")]
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            /* var applicationDbContext = _context.Report
                .Include(r => r.Set)
                .Include(r => r.ViewCount); */
            var reportset = await _context.Report
                .Include(r => r.Set)
                .Include(r => r.ViewCount)
                .ToListAsync();
            var ratings = await _context.SetRatingv3
                .ToListAsync();

            List<Report> reports = new();

            for (int i = 0; i < reportset.Count; i++)
            {
                Report report = new()
                {
                    ReportId = reportset[i].ReportId,
                    SetId = reportset[i].SetId,
                    Set = reportset[i].Set,
                    ViewCountId = reportset[i].ViewCountId,
                    ViewCount = reportset[i].ViewCount,
                    Ratings = ratings
                };
                report.CalculateAverageRating();
                reports.Add(report);
            }

            return View(reports);
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.ViewCount)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            
            if (report == null)
            {
                return NotFound();
            }

            // FlashcardSet set = GetSetById(report.SetId);
            FlashcardSet set = await _context.FlashcardSet
                .Include(s => s.User)
                .FirstOrDefaultAsync(s => s.SetId == report.SetId);
            report.Set = set;

            return View(report);
        }

        private FlashcardSet GetSetById(Guid SetId)
        { 
            return _context.FlashcardSet.FirstOrDefault(s => s.SetId == SetId);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
            ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name");
            return View();
        }

        private List<FlashcardSet> GetNonDeletedSets()
        {
            return _context.FlashcardSet.Where(set => !set.IsDeleted).ToList();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid SetId)
        {
            Report report = new() { SetId = SetId };

            // Check if there is already a report for the given SetId
            if (ReportExists(report.SetId))
            {
                ViewData["ErrorMessage"] = "A report already exists for this set.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            var set = await _context.FlashcardSet
                .FirstOrDefaultAsync(set => set.SetId == report.SetId);
            
            if (set == null)
            {
                ViewData["ErrorMessage"] = "This set does not exist.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            if (set.IsDeleted == true)
            {
                ViewData["ErrorMessage"] = "Cannot create a report on a deleted set.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            var ViewCount = await _context.ViewCount
                .FirstOrDefaultAsync(vc => vc.SetId == report.SetId);

            if (ViewCount == null)
            {
                ViewData["ErrorMessage"] = "Cannot create a report on a set without any views.";
                ViewData["SetId"] = new SelectList(GetNonDeletedSets(), "SetId", "Name", report.SetId);
                return View(report);
            }

            if (ModelState.IsValid)
            {
                report.ReportId = Guid.NewGuid();
                report.ViewCountId = ViewCount.ViewCountId;
                _context.Add(report);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(report);
        }

        // GET: Reports/Edit/5
        /* public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report.FindAsync(id);
            if (report == null)
            {
                return NotFound();
            }
            ViewData["ViewCountId"] = new SelectList(_context.ViewCount, "ViewCountId", "ViewCountId", report.ViewCountId);
            return View(report);
        } */

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /* [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ReportId,SetId,ViewCountId")] Report report)
        {
            if (id != report.ReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(report);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportExists(report.ReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ViewCountId"] = new SelectList(_context.ViewCount, "ViewCountId", "ViewCountId", report.ViewCountId);
            return View(report);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Report == null)
            {
                return NotFound();
            }

            var report = await _context.Report
                .Include(r => r.ViewCount)
                .FirstOrDefaultAsync(m => m.ReportId == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }
        */

        //POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Report == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Report'  is null.");
            }
            var report = await _context.Report.FindAsync(id);
            if (report != null)
            {
                _context.Report.Remove(report);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        } 

        private bool ReportExists(Guid id)
        {
            return (_context.Report?.Any(e => e.SetId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smart Cards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assignment4.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" integrity="sha384-IDaX67uymf7bFJTnGqJdas2mKfz+0XonrvcR/ZLiQBW4NCINz7BMJYwX+6tlg9y0" crossorigin="anonymous">
</head>
<body>
    <header>
        <partial name="_NavPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Smart Cards
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js" integrity="sha384-Ac/mQjmhtk+4qELB13f2LKT/9Uj31QqaXFKrEbmLtueYjPwTG6AXdzXqZSWWwUW1" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<style>
    #navBar{
        background: linear-gradient(113.9deg, rgb(255, 128, 0) -4.5%, rgb(255, 215, 0) 98.8%);
    }
    body{
        background: radial-gradient(circle at 10% 20%, rgb(255, 200, 124) 0%, rgb(252, 251, 121) 90%);
    }
</style>

<div id="navBar">
    <div class="d-grid p-3 px-md-4 mb-3 border-bottom box-shadow" style="grid-auto-flow: column">
        <div>
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="@Url.Content("~/logo.png")" width="120" /></a>
        </div>
        @if (SignInManager.IsSignedIn(User))
        {
          <nav class="d-flex gap-4">
                <a class="nav-link text-dark" asp-area="" asp-controller="FlashcardSets" asp-action="Index" id="navbar-text-justify">Sets</a>
            @if (User.IsInRole("Teacher"))
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="Flashcards" asp-action="Index" id="navbar-text-justify">Flashcards</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="PromotionRequests" asp-action="Index" id="navbar-text-justify">Manage Promotions</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index" id="navbar-text-justify">Reports</a>
            }
            @if (User.IsInRole("Student"))
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="PromotionRequests" asp-action="StudentView" id="navbar-text-justify">Get Promoted to Teacher</a>
                }
            </nav>
        }

          <div class="d-flex gap-4" id="nav-identity">
            @if (SignInManager.IsSignedIn(User))
            {
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" id="navbar-text-justify">@User.Identity?.Name</a>
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" id="navbar-text-justify">
                    <button type="submit" class="btn btn-outline-dark">Logout</button>
                </form>
            }
            else
            {
                    <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-outline-dark" id="register-login-justify">Register</a>
                    <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-outline-dark" id="register-login-justify">Login</a>
            }
          </div>
        </div>
</div>

<style>
    #register-login-justify {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    #register-login-justify:hover {
        color: black;
    }

    #navbar-text-justify {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>