Models/FlashcardSet.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace assignment4.Models
{
    public class FlashcardSet
    {
        [Key]
        public Guid SetId { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public string? Category { get; set; }
        [ForeignKey("AspNetUsers")]
        public string? UserId { get; set; }
        public IdentityUser? User { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public List<Flashcard>? Flashcards { get; set; }
        public FlashcardSet()
        {
            CreatedDate = DateTime.Now;
            IsDeleted = false;
        }
        public List<int> RandomCards() {
            int count = Flashcards.Count;
            int max = count;
            int min = 0;
            Random random = new();
            HashSet<int> set = new();

            while (set.Count < count)
            {
                set.Add(random.Next(min, max));
            }
            
            return set.ToList();
        }
    }
}

Controllers/FlashcardSetsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace assignment4.Controllers
{
    [Authorize]
    public class FlashcardSetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly string loggedInUserId;

        public FlashcardSetsController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            loggedInUserId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        // GET: FlashcardSets
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Index()
        {
            var sets = await _context.FlashcardSet
                .Where(f => f.IsDeleted == false)
                .Include(f => f.User)
                .ToListAsync();
            var ratings = await _context.SetRatingv3
                .ToListAsync();
            var views = await _context.ViewCount
                .ToListAsync();

            List<SetVM> setVMs = new();

            for(int i = 0; i < sets.Count; i++)
            {
                SetVM VM = new() {
                    Set = sets[i],
                };
                var id = VM.Set.SetId;

                var rating = ratings
                    .Where(r => r.RatedSetId == id)
                    .Average(r => r.Rating);
                if (rating != null)
                {
                    // This abomination gets the average rating (double), rounds it up or down, converts to a string, then converts to an int
                    VM.Rating.Rating = int.Parse(Math.Round(rating.Value, MidpointRounding.ToEven).ToString());
                }

                VM.Views = views
                    .FirstOrDefault(vc => vc.SetId == id);

                setVMs.Add(VM);
            }
         
            return View(setVMs);
        }

        // GET: FlashcardSets/Details/5
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.FlashcardSet == null)
            {
                return NotFound();
            }
            SetVM VM = new();

            VM.Set = await _context.FlashcardSet
                .Include(f => f.User)
                .Include(f => f.Flashcards.Where(f => f.SetId == id && f.IsDeleted == false))
                .FirstOrDefaultAsync(m => m.SetId == id);

            var rating = await _context.SetRatingv3
                .Where(sr => sr.RatedSetId == id)
                .AverageAsync(sr => sr.Rating);

            if(rating != null ) { 
                // This abomination gets the average rating (double), rounds it up or down, converts to a string, then converts to an int
                VM.Rating.Rating = int.Parse(Math.Round(rating.Value, MidpointRounding.ToEven).ToString());
            }

            VM.Views = await _context.ViewCount
                .FirstOrDefaultAsync(vc => vc.SetId == id);

            if (VM.Set == null)
            {
                return NotFound();
            }

            return View(VM);
        }

        // GET: FlashcardSets/Study/5
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Study(Guid? id)
        {
            if (id == null || _context.FlashcardSet == null)
            {
                return NotFound();
            }

            var flashcardSet = await _context.FlashcardSet
                .Include(f => f.User)
                .Include(f => f.Flashcards.Where(f => f.SetId == id && f.IsDeleted == false))
                .FirstOrDefaultAsync(m => m.SetId == id);
            if (flashcardSet == null)
            {
                return NotFound();
            }

            return View(flashcardSet);
        }

        // GET: FlashcardSets/Practice/5
        [Authorize(Roles = "Teacher, Student")]
        public async Task<IActionResult> Practice(Guid? id)
        {
            if (id == null || _context.FlashcardSet == null)
            {
                return NotFound();
            }

            var flashcardSet = await _context.FlashcardSet
                .Include(f => f.User)
                .Include(f => f.Flashcards.Where(f => f.SetId == id && f.IsDeleted == false))
                .FirstOrDefaultAsync(m => m.SetId == id);
            if (flashcardSet == null)
            {
                return NotFound();
            }

            return View(flashcardSet);
        }

        // GET: FlashcardSets/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["User"] = new SelectList(_context.Users, "UserName", "UserName");
            return View();
        }

        // POST: FlashcardSets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create([Bind("SetId,Name,Description,Category,CreatedDate,UpdatedDate,IsDeleted")] FlashcardSet flashcardSet)
        {
            if (ModelState.IsValid)
            {
                flashcardSet.SetId = Guid.NewGuid();

                // Automatically set the set UserId to the UserId of the logged in user.
                flashcardSet.UserId = loggedInUserId;

                flashcardSet.CreatedDate = DateTime.Now;
                flashcardSet.UpdatedDate = DateTime.Now;

                flashcardSet.IsDeleted = false;

                _context.Add(flashcardSet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", flashcardSet.UserId);
            return View(flashcardSet);
        }

        // GET: FlashcardSets/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.FlashcardSet == null)
            {
                return NotFound();
            }

            var flashcardSet = await _context.FlashcardSet
                .Include(f => f.Flashcards.Where(f => f.SetId == id && f.IsDeleted == false))
                .FirstAsync(m => m.SetId == id);
            // .FindAsync(id);
            if (flashcardSet == null)
            {
                return NotFound();
            }

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", flashcardSet.UserId);
            return View(flashcardSet);
        }

        // POST: FlashcardSets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(Guid id, [Bind("SetId,Name,Description,Category,UserId,CreatedDate,UpdatedDate,IsDeleted")] FlashcardSet flashcardSet)
        {
            if (id != flashcardSet.SetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    flashcardSet.UpdatedDate = DateTime.Now;
                    _context.Update(flashcardSet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlashcardSetExists(flashcardSet.SetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", flashcardSet.UserId);
            return View(flashcardSet);
        }

        // POST: FlashcardSets/Edit/5
        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> UpdateFlashcard(Guid setId, List<Flashcard> flashcards)
        {
            foreach (var flashcard in flashcards)
            {
                var flashcardId = flashcard.FlashcardId;
                flashcard.SetId = setId;
                flashcard.UpdatedDate = DateTime.Now;

                if (flashcardId != flashcard.FlashcardId)
                {
                    return NotFound();
                }

                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
            }

            _context.UpdateRange(flashcards);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FlashcardExists(flashcards[0].FlashcardId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: FlashcardSets/Delete/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.FlashcardSet == null)
            {
                return NotFound();
            }

            var flashcardSet = await _context.FlashcardSet
                .Include(f => f.User)

Controllers/PracticeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using assignment4.Data;
using assignment4.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Newtonsoft.Json;

namespace assignment4.Controllers
{
    public class AnswerModel
    {
        public Guid flashcardID { get; set; }
        public string selectedAnswer { get; set; }
    }
    [Authorize]
    public class PracticeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly string loggedInUserId;

        public PracticeController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            loggedInUserId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }


        [HttpPost]
        public IActionResult CheckAnswer([FromBody] AnswerModel answer)
        {
            bool isCorrect = true;
            var flashcard = _context.Flashcard
                .FirstOrDefault(m => m.FlashcardId == answer.flashcardID);

            if(answer.selectedAnswer == flashcard.Front) {
                isCorrect = true;
                return Content("Correct");
            } else {
                isCorrect = false;
                return Content("Incorrect");
            }
        }

    }
}

Views/FlashcardSets/Create.cshtml
@model assignment4.Models.FlashcardSet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FlashcardSet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">What do you want to name this set?</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Provide a brief description of this set.</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">Category:</label>
                <select asp-for="Category" class="form-control">
                    <option value="">-- Select a category --</option>
                    <option value="Art">Art</option>
                    <option value="Biology">Biology</option>
                    <option value="Business">Business</option>
                    <option value="Computer Science">Computer Science</option>
                    <option value="Engineering">Engineering</option>
                    <option value="English">English</option>
                    <option value="History">History</option>
                    <option value="Math">Math</option>
                    <option value="Psychology">Psychology</option>
                    <option value="Science">Science</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" id="padding-index"/>
            </div>
        </form>
        <div>
            <a asp-action="Index" class="btn btn-sm btn-secondary">Back to List</a>
        </div>
    </div>
</div>

<style>
    #padding-index {
        margin-bottom: 10px;
        margin-top: 10px;
    }
</style>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FlashcardSets/Delete.cshtml
@model assignment4.Models.FlashcardSet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flashcard Set</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
        <dt class = "col-sm-2">
            Created Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            Last updated
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SetId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

Views/FlashcardSets/Details.cshtml
@model assignment4.Models.SetVM

@{
    ViewData["Title"] = "Details";
    int filledStars = 0;
    int emptyStars = 0;
    if(Model.Rating.Rating.HasValue)
    {
        filledStars = Model.Rating.Rating.Value;
        emptyStars = 5 - filledStars;
    }
}
<div class="row">
    <div class="d-flex">
        <div class="col-md-2">
            <div class="row w-50">
                <a asp-action="Index" class="btn btn-dark" style="background-color: #000000; border-color: #000000">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left-fill" viewBox="0 0 16 16">
                <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z"/>
                </svg>
                </a>
            </div>
            <div class="row w-50">
                <a asp-action="Study" asp-route-id="@Model?.Set.SetId" class="btn btn-dark">Study</a>
            </div>
            <div class="row w-50">
                <a asp-action="Practice" asp-route-id="@Model?.Set.SetId" class="btn btn-secondary" style="background-color: #50585F; border-color: #50585F">Practice [BETA]</a>
            </div>
            <div class="row w-50">
            @if (User.IsInRole("Teacher"))
            {
                    <a asp-action="Edit" asp-route-id="@Model?.Set.SetId" class="btn btn-secondary">Edit</a>
            } 
            </div>
        </div>

        <div class="col-md-6 text-center">
            <h2>@Model.Set.Name</h2>
            <h3 class="lead">@Model.Set.Category</h3>
            <p>@Model.Set.Description</p>
            <p>Created: <i>@Model.Set.CreatedDate</i> | Updated: <i>@Model.Set.UpdatedDate</i></p>
        </div>

        <div class="col-md-2 d-flex flex-column text-center">
            @if(Model.Set.User != null)
            {
                <p><b>Created By:</b> @Model.Set.User.UserName</p>
            }
            @if (Model.Views != null)
            {
                <div class="mb-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"></path>
                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"></path>
                    </svg>
                    Studied @Model.Views.Count Times
                </div>
            }
            <div class="column">
                
                @if (Model.Rating.Rating.HasValue)
                {
                    <b>User Rating: </b>
                    @for (int i = 0; i < filledStars; i++)
                    {
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                        </svg>
                    }
                    @for (int i = 0; i < emptyStars; i++)
                    {
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z" />
                        </svg>
                    }
                }
                else
                {
                    <i>No ratings yet!</i>
                }
            </div>
            <a asp-action="Create" asp-controller="SetRatingv3" class="btn btn-secondary">Submit a rating</a>
        </div>
    </div>
</div>

<div class="d-flex">
    @if (Model.Set.Flashcards != null)
    {
        <table id="flashcards" class="table">
            <thead>
                <tr>
                    <th scope="col">Front</th>
                    <th scope="col">Back</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Set.Flashcards.Count; i++)
                {
                    var flashcard = Model.Set.Flashcards[i];
                    <tr>
                        <td>
                            <p id="front-@flashcard.FlashcardId" name="flashcards[@i].Front">@flashcard.Front</p>
                        </td>
                        <td>
                            <p id="back-@flashcard.FlashcardId" name="flashcards[@i].Back">@flashcard.Back</p>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Views/FlashcardSets/Study.cshtml
@model assignment4.Models.FlashcardSet

@{
    ViewData["Title"] = "Study";
}

<h1 class="text-center">Study</h1>

<div>
    <hr />
    <div class="text-center">
        <h2>@Model.Name</h2>
        <h3 class="lead">
            @Model.Category</h3>
            <p>@Model.Description</p>
    </div>
</div>

<body onload="updateViewCount()">
    @if (Model.Flashcards != null && Model.Flashcards.Count > 0)
    {
        <div class="d-flex">
            <div class="card mx-auto">
                <div class="card-body"  onclick="flipFlashcard()">
                        <h5 class="card-title" id="flashcardFront">@Model.Flashcards[0].Front</h5>
                        <h5 class="card-text d-none" id="flashcardBack">@Model.Flashcards[0].Back</h5>
                    </div>
            </div>
        </div>
        <div class="text-center">
            @if (Model.Flashcards.Count > 1)
            {
                <button class="arrow-btn prev" onclick="previousFlashcard()"></button>
                <button class="arrow-btn next" onclick="nextFlashcard()"></button>
            }
            <div class="frontOrBack" id="label">Front of card</div>
            <div class="card-count">
                <p id="cardNumber">1</p>
                <p>/</p>
                <p id="totalCardNumber">@Model.Flashcards.Count</p>
            </div>
            <button class="btn btn-dark" onclick="chatGPT()">Ask ChatGPT</button>
            <div id="chatgpt-response-area">

            </div>
        </div>
    }
    <div class="text-center" style="margin-top: 0.5rem;">
        @if (User.IsInRole("Teacher"))
        {
            <a asp-action="Edit" asp-route-id="@Model?.SetId" class="button">Edit</a>
        }
        <a asp-action="Index" class="button">Home</a>
        <a asp-controller="FlashcardSets" asp-action="Details" asp-route-id="@Model.SetId" class="button">Exit</a>
    </div>

    @{
        var serializerSettings = new Newtonsoft.Json.JsonSerializerSettings
            {
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
            };
        var flashcardsJson = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Flashcards, serializerSettings);
        var setJson = Newtonsoft.Json.JsonConvert.SerializeObject(Model, serializerSettings);
    }

    <style>
        .arrow-btn {
            background-color: #212529;
            color: #ffffff;
            border: none;
            border-radius: 80%;
            width: 60px;
            height: 60px;
            font-size: 30px;
            cursor: pointer;
            
        }
            .arrow-btn:hover {
                background-color: #333333;
            }

            .arrow-btn.prev:before {
                content: '\2190';
            }

            .arrow-btn.next:before {
                content: '\2192';
            }

        .card {
            width: 500px;
            height: 300px;
            background-color: white;
            border: 2px solid black;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
        }

        .card-body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100%;
            cursor: pointer;
        }

        .card:hover {
            background-color: lightgrey;
        }

        .card-title,
        .card-text {
            text-align: center;
        }

        .btn {
            margin-top: 1rem;
            font-size: 20px;
            padding: 12px 24px;
        }


        .frontOrBack {
            margin-top: 0.5rem;
            font-size: 16px;
        }

        #cardNumber{
            margin-right: 5px;
        }

        #totalCardNumber{
            margin-left: 5px;
        }

        .card-count p {
            display: inline-block
        }

        .button {
            display: inline-block;
            background-image: linear-gradient(113.9deg, rgb(255, 128, 0) -4.5%, rgb(255, 150, 0) 98.8%);
            color: black;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 4px;
        }

        .button:hover {
                background-image: none;
                background-color: darkgrey;
                color: black;
        }
    </style>

    <script>
        var set = @Html.Raw(setJson);
        function updateViewCount() {
            const setId = set.SetId;
            fetch('/ViewCounts/Increment/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ setId })
            })
        }

        var flashcards = @Html.Raw(flashcardsJson);
        var flashcardIndex = 0;
        var showingFront = true;

        function flipFlashcard() {
            var frontEl = document.querySelector("#flashcardFront");
            var backEl = document.querySelector("#flashcardBack");
            var labelEl = document.querySelector("#label");
            if (showingFront) {
                frontEl.classList.add("d-none");
                backEl.classList.remove("d-none");
                labelEl.innerHTML = "Back of card";
                showingFront = false;
            } else {
                backEl.classList.add("d-none");
                frontEl.classList.remove("d-none");
                labelEl.innerHTML = "Front of card";
                showingFront = true;
            }
        }

        function nextFlashcard() {
            var labelEl = document.querySelector("#label");
            flashcardIndex++;
            if (flashcardIndex >= flashcards.length) {
                flashcardIndex = 0;
            }
            document.querySelector("#flashcardFront").innerHTML = flashcards[flashcardIndex].Front;
            document.querySelector("#flashcardBack").innerHTML = flashcards[flashcardIndex].Back;
            labelEl.innerHTML = "Front of card";
            document.querySelector("#flashcardFront").classList.remove("d-none");
            document.querySelector("#flashcardBack").classList.add("d-none");

            updateCardNumber()
        }

        function previousFlashcard() 
        {
            var labelEl = document.querySelector("#label");
            flashcardIndex--;
            if (flashcardIndex < 0) {
                flashcardIndex = flashcards.length - 1;
            }
            document.querySelector("#flashcardFront").innerHTML = flashcards[flashcardIndex].Front;
            document.querySelector("#flashcardBack").innerHTML = flashcards[flashcardIndex].Back;
            labelEl.innerHTML = "Front of card";
            document.querySelector("#flashcardFront").classList.remove("d-none");
            document.querySelector("#flashcardBack").classList.add("d-none");

            updateCardNumber()
        }

        function updateCardNumber() 
        {
            var cardNumber = document.querySelector("#cardNumber");
            cardNumber.innerHTML = flashcardIndex + 1; // the + 1 is neeeded because the first card has an index of 0
        }

        function chatGPT() 
        {
            var searchTerm = 'Give me more information about the term: ' + flashcards[flashcardIndex].Front
            console.log('The prompt passed to ChatGPT is: ' + searchTerm)
            $('#chatgpt-response-area').html('<div class="spinner-border text-primary mt-3" role="status"><span class= "sr-only"></span></div>')

            $.ajax({
                type: "POST",
                url: "/OpenAI/AIResponse", // OpenAIController.cs
                data: {
                    prompt: searchTerm
                },
                success: function (response) {
                    $('#chatgpt-response-area').html("<p>" + response + "</p>")
                },
                error: function (xhr, status, error) {
                    console.log("An error occurred: " + error);
                    $('#chatgpt-response-area').html("<p>There was an error with ChatGPT :(</p>")
                }
            }); 

        }

    </script>

</body>